--SCRIPT USED TO INITIALIZE THE DB

CREATE TABLE main_table (
  event_id SERIAL PRIMARY KEY,
  user_id VARCHAR(512) NOT NULL,
  encryption VARCHAR(64) NOT NULL,
  time VARCHAR(512) NOT NULL,
  location_type VARCHAR(128) NOT NULL,
  location VARCHAR(512) NOT NULL,
  symptoms VARCHAR(4098) NOT NULL
);
